chore: add and populate amount & denom
fetchai/ledger-subquery pull request #66
Opened 2022-08-30 10:38 UTC by bryanchriswhite

### Changes
- add `amount` and `denom` fields to `DistDelegatorClaim`
- populate amount/denom with correlated "withdraw_reward" event
- simplify gql test query logic
- test IDs of related entities

2022-08-31 12:24 UTC, daeMOn63 requested changes

2022-08-31 13:28 UTC, bryanchriswhite commented on src/mappings/mappingHandlers.ts
> +  const amount_denom_split_regex = new RegExp(`^(\\d{1,${MAX_AMOUNT_CHAR_LENGTH}})(\\w{1,${MAX_DENOM_CHAR_LENGTH}})`);
Good looking out @daeMOn63!

2022-08-31 13:30 UTC, daeMOn63 approved these changes

2022-09-01 08:14 UTC, bryanchriswhite commented on src/mappings/mappingHandlers.ts
> +  const amount_denom_split_regex = new RegExp(`^(\\d{1,${MAX_AMOUNT_CHAR_LENGTH}})(\\w{1,${MAX_DENOM_CHAR_LENGTH}})`);
Attempting to import `parseCoins` via `@cosmjs/stargate` or `@cosmjs/proto-signing` packages caused the SubQuery node to crash shortly after starting up. Copying the impliementation from `@cosmjs/proto-signing` seems to work fine, despite importing `@cosmjs/amino` and `@cosmjs/math`. I suspect the fact that the SubQuery framework uses [vm2](https://github.com/patriksimek/vm2) to execute the code in mappingHandlers.ts is likely a contributing factor.

2022-09-01 08:19 UTC, daeMOn63 approved these changes

2022-09-01 09:45 UTC, merged